Amod Marathe - 25050123073

Experminet 10 - Study of Pandas library

In [2]:
# Introduction to Pandas
# Pandas : Panel Data
''' Used for :
structured data
'''
import pandas as pd
s = pd.Series([10,20,30,40,55])
s

0    10
1    20
2    30
3    40
4    55
dtype: int64

In [23]:
# create DataFrame
data  = {
    "Name": ["A","B","C"],
    "Marks": [85,90,78]
}
df = pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    C     78

In [24]:
# find struxture of the DataFrame
df.shape

(3, 2)

In [25]:
df.ndim
print(df.size)

6

In [26]:
# Display column Names
print(df.columns)

Index(['Name', 'Marks'], dtype='object')

In [27]:
print(df.dtypes)

Name     object
Marks     int64
dtype: object

In [29]:
# Access Individual column
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [14]:
df["Marks"]

0    10
1    20
2    30
Name: Marks, dtype: int64

In [30]:
df.loc[0,"Name"]

'A'

In [31]:
df =pd.DataFrame(data)
print(df)
print(df.loc[0,"Marks"])
print(df.iloc[2,1])

  Name  Marks
0    A     85
1    B     90
2    C     78
85
78

In [32]:
#Add  new column
''' If marks 80-90-first class
If Marks  >=90 - Distribution
If Marks >80 - second class'''
df["grade"]=["First Class","Distinction","Second Class"]
print(df)

  Name  Marks         grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [33]:
# Update Data in DataFrame
# Change marks of student A to 88.

df.iloc[0,1]=88
print(df)

  Name  Marks         grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class

In [34]:
# delete a column
df1=df.drop("grade",axis=1)
print(df)
print(df1)

  Name  Marks         grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class
  Name  Marks
0    A     88
1    B     90
2    C     78

In [35]:
# perform basic statistical analysis
mean1 = df["Marks"].mean()
mean1

np.float64(85.33333333333333)

In [37]:
min1 = df["Marks" ].min()
min1

78

In [38]:
max1=df["Marks"].max()
max1

90

In [39]:
# Apply condition (Filtering)
# Display students scoring more than 80.
df[df["Marks"]>80]

  Name  Marks        grade
0    A     88  First Class
1    B     90  Distinction